books = [
  {'_id':'0',
   'name': 'The Art Of War',
   'author': 'Sun Tzu',
   'cover':'../images/artofwar.jpg',
   'price': 7.69,
   'available': True,
   'qty': 10,
   'store':['Braintree','Boston','Quincy'],
   'rating': 5,
   'numReviews': 10
  },
  {'_id': '1',
   'name': '7 Habits of Highly Effective People',
   'author': 'Stephen R. Covey',
   'cover':'../images/7habits.jpg',
   'price': 24.88,
   'available': False,
   'qty': 5,
   'store':[],
   'rating': 4.5,
   'numReviews': 20
  },
  {'_id': '2',
   'name': 'Clean Code',
   'author': 'Robert C. Martin',
   'cover':'../images/cleancode.jpg',
   'price': 43.49,
   'available': False,
   'qty': 0,
   'store':[],
   'rating': 5,
   'numReviews': 27
  },
  {'_id': '3',
   'name': 'Atomic Habits',
   'author': 'James Clear',
   'cover':'../images/atomichabits.jpg',
   'price': 11.98,
   'available': True,
   'qty': 20,
   'store':['Boston', 'Quincy', 'Canton'],
   'rating': 0,
   'numReviews': 0
  },
]
